apiVersion: v1
kind: Service
metadata:
  name: community-postgres
spec:
  selector:
    app: community-postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5434
    targetPort: 5432
  type: ClusterIP
