apiVersion: v1
kind: Secret
metadata:
  name: community-postgres-secret
type: Opaque
data:
  db-name: Y29tbXVuaXR5X2Ri
  username: cG9zdGdyZXM=
  password: YWRtaW4=

---
apiVersion: v1
kind: Secret
metadata:
  name: community-service-secret
type: Opaque
data:
  secret-key: JG1temI3dl4mdDMhM2VxKWFtOWEtYStyPV96bzZvc3oycWExJik5KyZiZys1bnFhJT0=