apiVersion: v1
kind: Secret
metadata:
  name: user-postgres-secret
type: Opaque
data:
  username: dXNlcg==
  password: MTIzNA==
  db-name: dW1zX2Ri
  db-url: cG9zdGdyZXNxbDovL3VtczoxMjM0QHVzZXItcG9zdGdyZXMvdW1zX2Ri 