apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  smtp-username: Ym9nZGFuYm9nYTEyQGdtYWlsLmNvbQ==
  smtp-password: aG1hdiBkeXNvIHFmb2ggaXdsdg==
  smtp-from-email: Ym9nZGFuYm9nYTEyQGdtYWlsLmNvbQ==
  secret-key: JG1temI3dl4mdDMhM2VxKWFtOWEtYStyPV96bzZvc3oycWExJik5KyZiZys1bnFhJT0=