# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: redis
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: redis
#   template:
#     metadata:
#       labels:
#         app: redis
#     spec:
#       containers:
#       - name: redis
#         image: redis:7-alpine
#         env:
#         - name: REDIS_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: redis-secret
#               key: password
#         ports:
#         - containerPort: 6379
#         command: ["redis-server"]
#         args:
#           - "--requirepass"
#           - "$(REDIS_PASSWORD)"
