apiVersion: v1
kind: Secret
metadata:
  name: catalog-postgres-secret
type: Opaque
data:
  db-name: Y2F0YWxvZ19kYg==
  username: cG9zdGdyZXM=
  password: YWRtaW4=

---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
type: Opaque
data:
  secret-key: JG1temI3dl4mdDMhM2VxKWFtOWEtYStyPV96bzZvc3oycWExJik5KyZiZys1bnFhJT0=

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  access-key: bWluaW9hZG1pbg==
  secret-key: bWluaW9zZWNyZXQ=
